name: PlatformIO CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: cache PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: set up Python
      uses: actions/setup-python@v4
    - name: install platformio
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: install library dependencies
      run: pio lib -g install 1
    - name: create sample config.h
      run: cp include/config-sample.h include/config.h
    - name: create certs.h
      run: curl -s https://raw.githubusercontent.com/esp8266/Arduino/master/tools/cert.py | python3 - -s github.com -n pushgateway > include/certs.h
    - name: run platformio
      run: pio run
